import type { NextPage } from "next";
import Head from "next/head";
import { useMe } from "../lib/hooks";
import GradientLayout from "../components/GradientLayout";
import ArtistList from "../components/ArtistList";
import { Skeleton } from "@chakra-ui/react";

import { prisma } from "../lib/prisma";

const Home = ({ artists }) => {
  const { user, isLoading } = useMe();

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GradientLayout
        color="purple"
        roundedImage={true}
        subtitle="Profile"
        title={`${user?.firstName} ${user?.lastName}`}
        description={`${user?.playlistsCount} public playlists`}
        image={
          "https://dl.dropboxusercontent.com/s/bgiv0ssz3xpotz9/peep.png?dl=0"
        }
      >
        <ArtistList artists={artists} />
      </GradientLayout>
    </div>
  );
};

export const getServerSideProps = async () => {
  const artists = await prisma.artist.findMany({});

  return {
    props: { artists },
  };
};

export default Home;
