import type { NextPage } from "next";
import Head from "next/head";
import GradientLayout from "../components/GradientLayout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GradientLayout
        color="yellow"
        roundedImage={false}
        subtitle="Profile"
        title="Franklin Okolie"
        description="15 public playlist"
        image={
          "https://dl.dropboxusercontent.com/s/bgiv0ssz3xpotz9/peep.png?dl=0"
        }
      >
        <div>Home page</div>
      </GradientLayout>
    </div>
  );
};

export default Home;
